### PR TITLE
Read HPP_HOST and HPP_PORT

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
@nim65s can this be released on robotpkg ?

**Comment by nim65s** [comment]
Do you need a fast release of hpp-gui & hpp-plot, or can I make a release of all HPP ?

**Comment by jmirabel** [comment]
A fast release would help the creation of the docker for the demonstration on Tiago.

**Comment by nim65s** [comment]
ref. https://git.openrobots.org/issues/304

**Comment by jmirabel** [comment]
Amazing. Thank you for your promptness.

**Pull request merged**
